import { useState } from "react";
import { motion } from "framer-motion";
import { transactions, budgets, goals } from "../data/mockData";
import { Download, FileText, TrendingUp, TrendingDown } from "lucide-react";
import jsPDF from "jspdf";

export default function Reports() {
  const [activeReport, setActiveReport] = useState("monthly");

  const totalIncome = transactions.filter(t => t.amount > 0).reduce((a, b) => a + b.amount, 0);
  const totalExpense = transactions.filter(t => t.amount < 0).reduce((a, b) => a + Math.abs(b.amount), 0);
  const netSavings = totalIncome - totalExpense;
  const savingsRate = Math.round((netSavings / totalIncome) * 100);

  const reports = [
    { id: "monthly", label: "Monthly Report" },
    { id: "budget", label: "Budget Report" },
    { id: "goals", label: "Goals Report" },
  ];

  const handleExportPDF = () => {
    const doc = new jsPDF();

    doc.setFontSize(20);
    doc.setTextColor(99, 102, 241);
    doc.text("FinTrack — Financial Report", 20, 20);

    doc.setFontSize(12);
    doc.setTextColor(0, 0, 0);
    doc.text(`Report Type: ${activeReport.toUpperCase()}`, 20, 35);
    doc.text(`Generated: ${new Date().toLocaleDateString("en-IN")}`, 20, 45);

    doc.setDrawColor(200, 200, 200);
    doc.line(20, 50, 190, 50);

    if (activeReport === "monthly") {
      doc.setFontSize(14);
      doc.text("April 2026 — Monthly Summary", 20, 65);
      doc.setFontSize(11);
      doc.text(`Total Income:  +Rs.${totalIncome.toLocaleString()}`, 20, 80);
      doc.text(`Total Expense: -Rs.${totalExpense.toLocaleString()}`, 20, 92);
      doc.text(`Net Savings:    Rs.${netSavings.toLocaleString()}`, 20, 104);
      doc.text(`Savings Rate:   ${savingsRate}%`, 20, 116);
      doc.line(20, 122, 190, 122);
      doc.setFontSize(13);
      doc.text("Transactions", 20, 135);
      doc.setFontSize(10);
      transactions.forEach((t, i) => {
        const y = 148 + (i * 12);
        doc.text(`${t.date}  ${t.name}  (${t.category})`, 20, y);
        doc.text(`${t.amount > 0 ? "+" : "-"}Rs.${Math.abs(t.amount)}`, 160, y);
      });
    }

    if (activeReport === "budget") {
      doc.setFontSize(14);
      doc.text("Budget Performance Report", 20, 65);
      doc.setFontSize(11);
      budgets.forEach((b, i) => {
        const y = 80 + (i * 20);
        const pct = Math.round((b.spent / b.limit) * 100);
        doc.text(`${b.category}: Rs.${b.spent} / Rs.${b.limit} (${pct}% used)`, 20, y);
      });
    }

    if (activeReport === "goals") {
      doc.setFontSize(14);
      doc.text("Goals Progress Report", 20, 65);
      doc.setFontSize(11);
      goals.forEach((g, i) => {
        const y = 80 + (i * 20);
        const pct = Math.round((g.saved / g.target) * 100);
        doc.text(`${g.name}: Rs.${g.saved.toLocaleString()} / Rs.${g.target.toLocaleString()} (${pct}%)`, 20, y);
      });
    }

    doc.setFontSize(9);
    doc.setTextColor(150, 150, 150);
    doc.text("Generated by FinTrack — fintrack-dashboard-tau.vercel.app", 20, 280);
    doc.save(`fintrack-${activeReport}-report.pdf`);
  };

  return (
    <motion.div
      initial={{ opacity: 0 }}
      animate={{ opacity: 1 }}
      transition={{ duration: 0.4 }}
      className="flex flex-col gap-6"
    >
      <div className="flex items-center justify-between">
        <div>
          <h1 className="text-xl font-bold text-dark">Reports</h1>
          <p className="text-sm text-gray-400">Download and view financial reports</p>
        </div>
        <motion.button
          whileTap={{ scale: 0.95 }}
          onClick={handleExportPDF}
          className="flex items-center gap-2 px-4 py-2 bg-primary text-white text-sm font-semibold rounded-xl hover:bg-indigo-600 transition"
        >
          <Download size={16} />
          Export PDF
        </motion.button>
      </div>

      <div className="flex gap-2">
        {reports.map((r) => (
          <button
            key={r.id}
            onClick={() => setActiveReport(r.id)}
            className={`px-4 py-2 rounded-xl text-sm font-medium transition
              ${activeReport === r.id
                ? "bg-primary text-white"
                : "bg-white border border-gray-200 text-gray-500 hover:border-primary hover:text-primary"
              }`}
          >
            {r.label}
          </button>
        ))}
      </div>

      {activeReport === "monthly" && (
        <motion.div
          initial={{ opacity: 0, y: 10 }}
          animate={{ opacity: 1, y: 0 }}
          className="flex flex-col gap-4"
        >
          <div className="bg-dark text-white rounded-2xl p-6">
            <div className="flex items-center gap-2 mb-4">
              <FileText size={20} className="text-primary" />
              <h2 className="text-base font-semibold">April 2026 — Monthly Summary</h2>
            </div>
            <div className="grid grid-cols-2 lg:grid-cols-4 gap-4">
              {[
                { label: "Total Income", value: `+₹${totalIncome.toLocaleString()}`, color: "text-success" },
                { label: "Total Expense", value: `-₹${totalExpense.toLocaleString()}`, color: "text-danger" },
                { label: "Net Savings", value: `₹${netSavings.toLocaleString()}`, color: "text-primary" },
                { label: "Savings Rate", value: `${savingsRate}%`, color: "text-warning" },
              ].map((item, i) => (
                <div key={i} className="bg-white/10 rounded-xl p-3">
                  <p className="text-xs text-gray-400">{item.label}</p>
                  <p className={`text-lg font-bold ${item.color}`}>{item.value}</p>
                </div>
              ))}
            </div>
          </div>
          <div className="bg-white rounded-2xl p-5 shadow-sm border border-gray-100">
            <h2 className="text-base font-semibold text-dark mb-4">Transaction Breakdown</h2>
            <div className="flex flex-col gap-3">
              {transactions.map((t, i) => (
                <motion.div
                  key={t.id}
                  initial={{ opacity: 0, x: -10 }}
                  animate={{ opacity: 1, x: 0 }}
                  transition={{ delay: i * 0.05 }}
                  className="flex items-center justify-between py-2 border-b border-gray-50 last:border-0"
                >
                  <div className="flex items-center gap-3">
                    <div className={`w-8 h-8 rounded-xl flex items-center justify-center
                      ${t.amount > 0 ? "bg-success/10" : "bg-danger/10"}`}>
                      {t.amount > 0
                        ? <TrendingUp size={14} className="text-success" />
                        : <TrendingDown size={14} className="text-danger" />}
                    </div>
                    <div>
                      <p className="text-sm font-medium text-dark">{t.name}</p>
                      <p className="text-xs text-gray-400">{t.category} · {t.date}</p>
                    </div>
                  </div>
                  <span className={`text-sm font-bold ${t.amount > 0 ? "text-success" : "text-danger"}`}>
                    {t.amount > 0 ? "+" : "-"}₹{Math.abs(t.amount).toLocaleString()}
                  </span>
                </motion.div>
              ))}
            </div>
          </div>
        </motion.div>
      )}

      {activeReport === "budget" && (
        <motion.div
          initial={{ opacity: 0, y: 10 }}
          animate={{ opacity: 1, y: 0 }}
          className="flex flex-col gap-4"
        >
          <div className="bg-white rounded-2xl p-5 shadow-sm border border-gray-100">
            <h2 className="text-base font-semibold text-dark mb-4">Budget Performance</h2>
            {budgets.map((b, i) => (
              <motion.div
                key={i}
                initial={{ opacity: 0, y: 10 }}
                animate={{ opacity: 1, y: 0 }}
                transition={{ delay: i * 0.1 }}
                className="flex items-center gap-4 py-3 border-b border-gray-50 last:border-0"
              >
                <div className="w-32 text-sm font-medium text-dark">{b.category}</div>
                <div className="flex-1 h-2 bg-gray-100 rounded-full overflow-hidden">
                  <motion.div
                    initial={{ width: 0 }}
                    animate={{ width: `${Math.round((b.spent / b.limit) * 100)}%` }}
                    transition={{ duration: 0.8 }}
                    className={`h-full rounded-full ${
                      Math.round((b.spent / b.limit) * 100) >= 90 ? "bg-danger" :
                      Math.round((b.spent / b.limit) * 100) >= 70 ? "bg-warning" : "bg-primary"
                    }`}
                  />
                </div>
                <div className="text-right w-32">
                  <p className="text-xs font-semibold text-dark">₹{b.spent} / ₹{b.limit}</p>
                  <p className="text-xs text-gray-400">{Math.round((b.spent / b.limit) * 100)}% used</p>
                </div>
              </motion.div>
            ))}
          </div>
        </motion.div>
      )}

      {activeReport === "goals" && (
        <motion.div
          initial={{ opacity: 0, y: 10 }}
          animate={{ opacity: 1, y: 0 }}
          className="flex flex-col gap-4"
        >
          <div className="bg-white rounded-2xl p-5 shadow-sm border border-gray-100">
            <h2 className="text-base font-semibold text-dark mb-4">Goals Progress Report</h2>
            {goals.map((g, i) => (
              <motion.div
                key={i}
                initial={{ opacity: 0, y: 10 }}
                animate={{ opacity: 1, y: 0 }}
                transition={{ delay: i * 0.1 }}
                className="flex items-center gap-4 py-3 border-b border-gray-50 last:border-0"
              >
                <div className="w-32 text-sm font-medium text-dark">{g.name}</div>
                <div className="flex-1 h-2 bg-gray-100 rounded-full overflow-hidden">
                  <motion.div
                    initial={{ width: 0 }}
                    animate={{ width: `${Math.round((g.saved / g.target) * 100)}%` }}
                    transition={{ duration: 0.8 }}
                    className="h-full rounded-full bg-success"
                  />
                </div>
                <div className="text-right w-40">
                  <p className="text-xs font-semibold text-dark">
                    ₹{g.saved.toLocaleString()} / ₹{g.target.toLocaleString()}
                  </p>
                  <p className="text-xs text-gray-400">
                    {Math.round((g.saved / g.target) * 100)}% achieved
                  </p>
                </div>
              </motion.div>
            ))}
          </div>
        </motion.div>
      )}
    </motion.div>
  );
}
